# This file contains the parameters to use to create the experiment template

experiment_parameters:
  wave_amplitude_range: [0.1]
  wave_frequency_range: [3]
  square_dimension_perc_range: [0.5]
  line_thickness_perc_range: [0.00, 0.03]
  line_dimension_perc_range: [0.66]
  line_angle_range: [30]
