# This file contains the parameters to use to create the experiment template

# Distortion Experiment
experiment_parameters:
  wave_amplitude_range: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
  square_dimension_perc_range: [0.0]
  line_thickness_perc_range: [] # must be empty
  line_dimension_perc_range: [] # must be empty
  line_angle_range: [] # must be empty
