# This file contains the parameters to use to create the experiment template

# Square Experiment
experiment_parameters:
  wave_amplitude_range: [0]
  wave_frequency_range: [2]
  square_dimension_perc_range: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  line_thickness_perc_range: [0]
  line_dimension_perc_range: [0]
  line_angle_range: [0]
