# This file contains the parameters to use to create the experiment template

# Distortion Experiment
experiment_parameters:
  wave_amplitude_range: [0.0, 0.25, 0.5, 0.75, 1]
  square_dimension_perc_range: [0.0]
  line_thickness_perc_range: []
  line_dimension_perc_range: []
  line_angle_range: []
